name: Build coova-chilli with JSON support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev \
            file wget python3-setuptools python3-dev python-is-python3

      - name: Download and extract OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt76x8/openwrt-sdk-23.05.4-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Clone coova-chilli from OpenWrt packages feed
        run: |
          git clone https://github.com/openwrt/packages.git
          mkdir -p sdk/package/coova
          mv packages/net/coova-chilli sdk/package/coova/

      - name: Configure build with JSON support
        run: |
          cd sdk
          echo "CONFIG_PACKAGE_coova-chilli=m" >> .config
          echo "CONFIG_COOVACHILLI_JSONINTERFACE=y" >> .config
          make defconfig

      - name: Build coova-chilli
        run: |
          cd sdk
          make package/coova/chilli/compile V=s

      - name: Upload .ipk
        uses: actions/upload-artifact@v4
        with:
          name: coova-chilli-ipk
          path: |
            sdk/bin/packages/mipsel_24kc/*/coova-chilli_*.ipk
            sdk/bin/targets/ramips/mt76x8/packages/coova-chilli_*.ipk
