name: Build coova-chilli with JSON support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev \
            file wget python3-setuptools python3-dev python-is-python3

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt76x8/openwrt-sdk-23.05.4-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Clone OpenWISP CoovaChilli
        run: |
          git clone https://github.com/openwisp/coova-chilli-openwrt.git sdk/package/coova-chilli

      - name: Build CoovaChilli
        run: |
          cd sdk
          echo "CONFIG_PACKAGE_coova-chilli=m" >> .config
          echo "CONFIG_COOVACHILLI_JSONINTERFACE=y" >> .config
          make defconfig
          make package/coova-chilli/compile V=s

      - name: Upload built IPK
        uses: actions/upload-artifact@v4
        with:
          name: coova-chilli-ipk
          path: |
            sdk/bin/packages/mipsel_24kc/*/coova-chilli_*.ipk
            sdk/bin/targets/ramips/mt76x8/packages/coova-chilli_*.ipk
